# Generated by Django 5.2.16 on 2026-07-30 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Menor número = aparece primero.')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('bajada', models.CharField(blank=True, help_text='Una línea, tono CHAO.', max_length=220)),
                ('ruta_estatica', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(blank=True, upload_to='looks/')),
                ('alt', models.CharField(blank=True, max_length=180)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Por ejemplo: S, M, L, 38, 40.', max_length=10, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_a_confirmar', models.BooleanField(default=True, help_text='Tildado = se muestra el aviso de que el precio es estimado y falta confirmarlo.', verbose_name='precio de referencia')),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False, help_text='Aparece primero en el catálogo.')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_estatica', models.CharField(blank=True, help_text='Ruta dentro de static/, por ejemplo img/productos/sweater.jpg', max_length=200)),
                ('imagen', models.ImageField(blank=True, upload_to='productos/')),
                ('alt', models.CharField(blank=True, max_length=180)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imágenes',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, help_text='Posición horizontal en % (0-100).', max_digits=5)),
                ('y', models.DecimalField(decimal_places=2, help_text='Posición vertical en % (0-100).', max_digits=5)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogo.look')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_looks', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'prenda del look',
                'verbose_name_plural': 'prendas del look',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('look', 'producto'), name='producto_una_vez_por_look')],
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='catalogo.talle')),
            ],
            options={
                'ordering': ['talle__orden', 'talle__nombre'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'talle'), name='variante_unica_por_talle')],
            },
        ),
    ]
