# Generated by Django 5.2.17 on 2026-10-02 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='etiqueta',
            field=models.CharField(blank=True, help_text='Cartel corto sobre la foto: "Nuevo", "Tendencia", "Edición limitada"…', max_length=24),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si está cargado y es mayor que el precio, la prenda se muestra en oferta.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(default='Otoño / 26', max_length=40)),
                ('frase', models.CharField(default='Ropa para cada versión tuya.', max_length=120)),
                ('bajada_coleccion', models.CharField(default='Las piezas que acaban de llegar al local. Agregalas directo o pasá a probarlas.', max_length=200)),
                ('foto_hero', models.ForeignKey(blank=True, help_text='Si no hay ninguna elegida, se usa la primera foto de look activa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogo.look')),
            ],
            options={
                'verbose_name': 'portada',
                'verbose_name_plural': 'portada',
            },
        ),
    ]
